### ISSUE TITLE
Db init scripts are outdated

### ISSUE THREAD

**Issue by deneirgits** [Resgrid/resgrid-setup#2]
From https://hub.docker.com/r/microsoft/mssql-server 

> Note Starting with SQL Server 2022 CU 14, we are updating SQL Server 2022 container images to include the new mssql-tools18 package. With the introduction of SQL Server 2022 CU 14, and in all future container images, the previous directory /opt/mssql-tools/bin will be phased out. The new directory for Microsoft ODBC 18 tools will be '/opt/mssql-tools18/bin', aligning with the latest tools offering.

Which makes these lines outdated:
https://github.com/Resgrid/resgrid-setup/blob/master/db/initdbs.sh#L2
https://github.com/Resgrid/resgrid-setup/blob/master/db/run-initialization.sh#L6

**Comment by ucswift** [comment]
Hey @deneirgits, thank you! I've merged your fix (thank you again) and I'm working on the setup scripts right now and will have a few more fixes here shortly.
